// Valores por 100 g (o 100 ml) de alimento, redondeados, tomados como referencia de USDA FoodData Central.
// Son estimaciones: pueden variar según marca, cocción y origen. Verifica con la etiqueta cuando sea posible.
export const FUENTE='Valores de referencia por 100 g basados en USDA FoodData Central, redondeados; son estimaciones, no mediciones. Carbohidratos netos = carbohidratos totales − fibra (definición simple; las etiquetas pueden calcularlo distinto).';
const A=[
// id, nombre, categoría, kcal, proteínas, carbohidratos, fibra, grasas
['huevo','Huevo entero','proteina',143,12.6,.7,0,9.5],
['pollo','Pechuga de pollo cocida','proteina',165,31,0,0,3.6],
['carne','Carne vacuna magra cocida','proteina',217,26,0,0,12],
['atun','Atún al natural','proteina',116,26,0,0,1],
['salmon','Salmón cocido','proteina',206,22,0,0,12],
['merluza','Merluza cocida','proteina',90,19,0,0,1.3],
['mozzarella','Queso mozzarella','lacteo',254,24,3,0,16],
['ricota','Ricota','lacteo',174,11,3,0,13],
['yogur','Yogur griego natural','lacteo',59,10,3.6,0,.4],
['leche','Leche entera','lacteo',61,3.2,4.8,0,3.3],
['espinaca','Espinaca','verdura',23,2.9,3.6,2.2,.4],
['brocoli','Brócoli','verdura',34,2.8,6.6,2.6,.4],
['zapallito','Zapallito / zucchini','verdura',17,1.2,3.1,1,.3],
['tomate','Tomate','verdura',18,.9,3.9,1.2,.2],
['cebolla','Cebolla','verdura',40,1.1,9.3,1.7,.1],
['lechuga','Lechuga','verdura',15,1.4,2.9,1.3,.2],
['pepino','Pepino','verdura',15,.7,3.6,.5,.1],
['pimiento','Pimiento','verdura',31,1,6,2.1,.3],
['coliflor','Coliflor','verdura',25,1.9,5,2,.3],
['zanahoria','Zanahoria','verdura',41,.9,9.6,2.8,.2],
['palta','Palta (aguacate)','grasa',160,2,8.5,6.7,14.7],
['aceite','Aceite de oliva','grasa',884,0,0,0,100],
['mantequilla','Mantequilla','grasa',717,.9,.1,0,81],
['almendras','Almendras','grasa',579,21,22,12.5,50],
['nueces','Nueces','grasa',654,15,14,6.7,65],
['chia','Semillas de chía','grasa',486,17,42,34,31],
['avena','Avena en hojuelas','cereal',389,17,66,10.6,7],
['arroz','Arroz blanco cocido','cereal',130,2.7,28,.4,.3],
['mandioca','Mandioca cocida','cereal',160,1.4,38,1.8,.3],
['batata','Batata cocida','cereal',90,2,21,3.3,.2],
['fideos','Fideos cocidos','cereal',158,5.8,31,1.8,.9],
['pan','Pan integral','cereal',247,13,41,7,3.4],
['lentejas','Lentejas cocidas','legumbre',116,9,20,7.9,.4],
['porotos','Porotos negros cocidos','legumbre',132,8.9,24,8.7,.5],
['banana','Banana','fruta',89,1.1,23,2.6,.3],
['manzana','Manzana','fruta',52,.3,14,2.4,.2],
['frutilla','Frutilla','fruta',32,.7,7.7,2,.3],
['naranja','Naranja','fruta',47,.9,12,2.4,.1],
['higado','Hígado vacuno cocido','proteina',175,27,5.1,0,4.7],
['mondongo','Mondongo cocido','proteina',100,15,0,0,4],
['rinon','Riñón vacuno cocido','proteina',158,27,0,0,4.5],
['lengua','Lengua vacuna cocida','proteina',283,19,0,0,22],
['surubi','Surubí cocido (ref. pez de río)','proteina',152,19,0,0,8],
['tilapia','Tilapia cocida','proteina',128,26,0,0,2.7],
['molida','Carne molida cocida','proteina',230,26,0,0,13],
['qparaguay','Queso Paraguay (ref. queso fresco)','lacteo',299,18,3,0,24],
['repollo','Repollo','verdura',25,1.3,5.8,2.5,.1],
['zapallo','Zapallo','verdura',26,1,6.5,.5,.1],
['papa','Papa hervida','cereal',87,1.9,20,1.8,.1],
['choclo','Choclo (maíz tierno) cocido','cereal',96,3.4,21,2.4,1.5],
['hmaiz','Harina de maíz','cereal',361,6.9,77,7.3,3.9],
['cacao','Cacao amargo en polvo','grasa',228,19.6,57.9,33.2,13.7],
['garbanzos','Garbanzos cocidos','legumbre',164,8.9,27.4,7.6,2.6],
['mani','Maní tostado sin sal','grasa',585,24,21,8,50],
['lino','Semillas de lino (linaza)','grasa',534,18,29,27,42],
['mamon','Mamón (papaya)','fruta',43,.5,10.8,1.7,.3],
['melon','Melón','fruta',34,.8,8.2,.9,.2],
['guayaba','Guayaba','fruta',68,2.6,14.3,5.4,.9],
['pomelo','Pomelo','fruta',42,.8,10.7,1.6,.1],
['arveja','Arvejas cocidas','verdura',84,5.4,15.6,5.5,.2],
['berenjena','Berenjena cocida','verdura',35,.8,8.7,2.5,.2],
['acelga','Acelga cocida','verdura',20,1.9,4.1,2.1,.1],
['remolacha','Remolacha cocida','verdura',44,1.7,10,2,.2],
['chaucha','Chauchas cocidas','verdura',35,1.9,7.9,3.2,.3]
];
export const MAR=new Set(['salmon','merluza']);
export const CARO=new Set(['nueces','almendras','chia','palta']);
const PESC=new Set(['atun','salmon','merluza','surubi','tilapia']);
export const SECCIONES={carnes:'Carnes y vísceras',pescados:'Pescados',huevos:'Huevos',lacteos:'Lácteos',verduras:'Verduras',frutas:'Frutas',despensa:'Despensa',condimentos:'Condimentos',otros:'Otros'};
export function seccion(a){if(!a)return 'otros';if(a.id==='huevo')return 'huevos';if(PESC.has(a.id))return 'pescados';return {proteina:'carnes',lacteo:'lacteos',verdura:'verduras',fruta:'frutas'}[a.cat]||'despensa';}
export const ALIMENTOS=A.map(([id,n,cat,kcal,p,c,fi,g])=>({id,n,cat,kcal,p,c,fi,g,base:true}));
const R=(id,n,tags,por,t,ing,pasos)=>({id,n,tags,por,t,ing,pasos,base:true});
export const RECETAS=[
R('r1','Omelette de espinaca y queso',['desayuno'],1,10,[['huevo',150],['espinaca',50],['mozzarella',30],['aceite',5]],['Bate los huevos con una pizca de sal.','Saltea la espinaca 1 minuto en una sartén con el aceite.','Agrega los huevos y el queso, cocina a fuego medio y dobla.']),
R('r2','Huevos revueltos con palta',['desayuno'],1,10,[['huevo',150],['palta',70],['tomate',50],['aceite',5]],['Revuelve los huevos en una sartén con el aceite.','Sirve con la palta en rodajas y el tomate picado.']),
R('r3','Yogur griego con frutillas y nueces',['desayuno'],1,5,[['yogur',200],['frutilla',100],['nueces',15]],['Coloca el yogur en un bowl.','Agrega las frutillas cortadas y las nueces picadas.']),
R('r4','Avena con chía y manzana',['desayuno'],1,10,[['avena',40],['leche',200],['chia',10],['manzana',80]],['Calienta la leche con la avena 4 a 5 minutos.','Agrega la chía y la manzana picada.']),
R('r5','Pollo a la plancha con ensalada',['almuerzo','cena'],1,20,[['pollo',180],['lechuga',80],['tomate',80],['pepino',50],['aceite',10]],['Cocina el pollo en plancha caliente hasta que esté bien cocido.','Mezcla las verduras cortadas y alíñalas con el aceite.']),
R('r6','Carne con brócoli salteado',['almuerzo','cena'],1,25,[['carne',150],['brocoli',150],['cebolla',40],['aceite',10]],['Corta la carne en tiras y dórala en la sartén.','Agrega la cebolla y el brócoli y saltea 6 a 8 minutos.']),
R('r7','Merluza al horno con zapallito',['almuerzo','cena'],1,30,[['merluza',200],['zapallito',150],['aceite',10],['tomate',50]],['Coloca todo en una fuente con el aceite y sal.','Hornea a 200 °C unos 20 minutos.']),
R('r8','Ensalada de atún y huevo',['almuerzo','cena'],1,15,[['atun',120],['huevo',50],['lechuga',100],['tomate',80],['palta',40],['aceite',5]],['Cocina el huevo 10 minutos y pícalo.','Mezcla todos los ingredientes en un bowl.']),
R('r9','Salmón con coliflor',['almuerzo','cena'],1,25,[['salmon',150],['coliflor',200],['aceite',8]],['Hornea el salmón a 200 °C unos 12 a 15 minutos.','Saltea o hierve la coliflor y sirve junto.']),
R('r10','Tortilla de zapallito',['almuerzo','cena'],1,20,[['huevo',150],['zapallito',150],['cebolla',30],['mozzarella',30],['aceite',8]],['Saltea el zapallito y la cebolla.','Agrega los huevos batidos y el queso y cocina de ambos lados.']),
R('r11','Pollo con arroz y verduras',['almuerzo','cena'],1,30,[['pollo',150],['arroz',150],['zanahoria',60],['brocoli',80],['aceite',8]],['Cocina el pollo en cubos con el aceite.','Agrega las verduras picadas y el arroz cocido y mezcla.']),
R('r12','Guiso de lentejas con carne',['almuerzo'],2,45,[['lentejas',400],['carne',160],['zanahoria',100],['cebolla',80],['aceite',10]],['Dora la carne con la cebolla y la zanahoria.','Agrega las lentejas cocidas y un poco de agua; cocina 15 minutos.']),
R('r13','Pollo al horno con batata',['cena'],1,40,[['pollo',180],['batata',150],['pimiento',80],['aceite',8]],['Coloca todo en una fuente con el aceite y sal.','Hornea a 200 °C unos 30 minutos.']),
R('r14','Almendras y manzana',['colacion'],1,2,[['almendras',20],['manzana',100]],['Come las almendras junto con la manzana en trozos.']),
R('r15','Yogur con chía',['colacion'],1,3,[['yogur',150],['chia',8]],['Mezcla el yogur con la chía y deja reposar unos minutos.']),
R('r16','Hígado encebollado',['almuerzo','cena'],1,20,[['higado',150],['cebolla',80],['pimiento',40],['aceite',8]],['Cocina la cebolla y el pimiento en rodajas con el aceite hasta que se ablanden.','Agrega el hígado en bifes finos y cocina 3 a 4 minutos por lado.']),
R('r17','Mondongo guisado',['almuerzo','cena'],1,60,[['mondongo',200],['tomate',100],['cebolla',60],['pimiento',50],['zanahoria',50],['aceite',8]],['Usa mondongo bien lavado y hervido previamente.','Sofríe cebolla, pimiento y tomate; agrega el mondongo, la zanahoria y un poco de agua.','Cocina a fuego bajo hasta que esté tierno.']),
R('r18','Riñón salteado con cebolla y tomate',['almuerzo','cena'],1,25,[['rinon',150],['cebolla',60],['tomate',80],['aceite',8]],['Remoja el riñón en agua con limón o vinagre, hiérvelo una vez y descarta esa agua.','Saltea la cebolla y el tomate; agrega el riñón en trozos y cocina 5 minutos.']),
R('r19','Lengua a la vinagreta',['almuerzo','cena'],1,20,[['lengua',150],['tomate',80],['cebolla',40],['pimiento',40],['aceite',8]],['Corta la lengua ya cocida en rebanadas.','Pica tomate, cebolla y pimiento; alíñalos con el aceite y sirve sobre la lengua.']),
R('r20','Bife a la plancha con ensalada',['almuerzo','cena'],1,20,[['carne',180],['lechuga',80],['tomate',80],['cebolla',30],['aceite',8]],['Cocina el bife en plancha caliente al punto que prefieras.','Sirve con la ensalada alíñada con el aceite.']),
R('r21','Hamburguesa casera con ensalada',['almuerzo','cena'],1,20,[['molida',180],['huevo',50],['lechuga',80],['tomate',80],['aceite',5]],['Mezcla la carne con el huevo y sal; forma una o dos hamburguesas.','Cocina en plancha 4 minutos por lado y sirve con ensalada.']),
R('r22','Soyo liviano de carne molida',['almuerzo','cena'],1,35,[['molida',150],['zanahoria',60],['cebolla',50],['tomate',80],['zapallo',100],['papa',80],['aceite',5]],['Sofríe la cebolla y la carne molida con el aceite.','Agrega tomate, zanahoria, zapallo y papa en cubos con agua.','Cocina 20 minutos hasta que espese. Adaptación casera, puede variar según la zona.']),
R('r23','Guiso de pollo con verduras',['almuerzo','cena'],1,40,[['pollo',200],['zapallo',150],['zanahoria',60],['cebolla',50],['pimiento',50],['tomate',80],['aceite',8]],['Dora el pollo en trozos con el aceite.','Agrega las verduras picadas y un poco de agua.','Cocina tapado a fuego bajo 25 minutos.']),
R('r24','Pollo desmenuzado con repollo',['almuerzo','cena'],1,20,[['pollo',170],['repollo',150],['zanahoria',40],['aceite',8]],['Desmenuza el pollo cocido.','Saltea el repollo y la zanahoria rallada con el aceite 5 minutos y mezcla con el pollo.']),
R('r25','Caldo de pollo con verduras',['almuerzo','cena'],1,35,[['pollo',150],['zanahoria',60],['zapallo',100],['cebolla',40]],['Hierve el pollo con las verduras en agua con sal.','Cocina 25 minutos y sirve caliente.']),
R('r26','Pollo al horno con zapallo',['almuerzo','cena'],1,40,[['pollo',180],['zapallo',200],['cebolla',40],['aceite',8]],['Coloca todo en una fuente con el aceite y sal.','Hornea a 200 °C unos 30 minutos.']),
R('r27','Surubí a la plancha con ensalada',['almuerzo','cena'],1,20,[['surubi',200],['lechuga',80],['tomate',80],['aceite',8]],['Cocina el surubí en plancha 4 a 5 minutos por lado.','Sirve con la ensalada alíñada con el aceite.']),
R('r28','Surubí al horno con verduras',['almuerzo','cena'],1,30,[['surubi',200],['zapallito',100],['pimiento',60],['cebolla',40],['aceite',8]],['Coloca el pescado y las verduras en una fuente con el aceite.','Hornea a 200 °C unos 20 minutos.']),
R('r29','Tilapia al horno con repollo',['almuerzo','cena'],1,30,[['tilapia',200],['repollo',150],['tomate',60],['aceite',8]],['Hornea la tilapia con el tomate y el aceite a 200 °C unos 18 minutos.','Saltea el repollo y sirve junto.']),
R('r30','Tilapia a la plancha con ensalada de pepino',['almuerzo','cena'],1,20,[['tilapia',200],['pepino',100],['tomate',80],['aceite',8]],['Cocina la tilapia en plancha 4 minutos por lado.','Sirve con pepino y tomate en rodajas.']),
R('r31','Mandioca hervida con huevo y ensalada',['almuerzo','cena'],1,25,[['mandioca',150],['huevo',100],['lechuga',80],['tomate',80],['aceite',5]],['Hierve la mandioca hasta que esté tierna.','Prepara los huevos duros y sirve con ensalada.']),
R('r32','Guiso de carne con mandioca',['almuerzo'],1,50,[['carne',150],['mandioca',150],['zanahoria',60],['cebolla',50],['tomate',80],['aceite',8]],['Dora la carne en cubos con el aceite.','Agrega las verduras y la mandioca con agua y cocina 35 minutos.']),
R('r33','Batata asada con huevo',['desayuno','almuerzo'],1,30,[['batata',150],['huevo',100],['espinaca',40],['aceite',5]],['Hornea la batata hasta que esté tierna.','Prepara los huevos revueltos con la espinaca y sirve juntos.']),
R('r34','Ensalada de lechuga, tomate y huevo',['almuerzo','cena'],1,12,[['lechuga',120],['tomate',100],['huevo',100],['aceite',8]],['Cocina los huevos 10 minutos.','Mezcla las verduras con el huevo picado y el aceite.']),
R('r35','Ensalada de repollo y zanahoria con pollo',['almuerzo','cena'],1,15,[['repollo',150],['zanahoria',50],['pollo',150],['aceite',10]],['Ralla el repollo y la zanahoria.','Agrega el pollo desmenuzado y el aceite y mezcla.']),
R('r36','Ensalada de lentejas con verduras',['almuerzo','cena'],1,15,[['lentejas',150],['tomate',80],['pepino',60],['cebolla',30],['aceite',8]],['Mezcla las lentejas ya cocidas con las verduras picadas.','Alíña con el aceite.']),
R('r37','Huevos duros con ensalada',['almuerzo','cena'],1,15,[['huevo',150],['lechuga',100],['tomate',80],['aceite',5]],['Cocina los huevos 10 minutos.','Sirve con la ensalada.']),
R('r38','Huevos al horno con tomate y queso',['desayuno','cena'],1,20,[['huevo',150],['tomate',100],['qparaguay',30],['cebolla',30],['aceite',5]],['Coloca tomate y cebolla picados en una fuente con el aceite.','Agrega los huevos y el queso y hornea 12 minutos.']),
R('r39','Revuelto de huevo con tomate y cebolla',['desayuno'],1,10,[['huevo',150],['tomate',80],['cebolla',40],['aceite',5]],['Saltea la cebolla y el tomate.','Agrega los huevos batidos y revuelve hasta que cuajen.']),
R('r40','Tortilla de repollo',['almuerzo','cena'],1,20,[['huevo',150],['repollo',100],['cebolla',30],['aceite',8]],['Saltea el repollo y la cebolla.','Agrega los huevos batidos y cocina de ambos lados.']),
R('r41','Chipa guasu',['almuerzo','cena'],4,50,[['choclo',300],['huevo',100],['qparaguay',120],['leche',100],['cebolla',60],['aceite',20]],['Procesa o tritura el choclo y mezcla con huevos, leche, queso en cubos y cebolla salteada.','Vierte en una fuente aceitada y hornea a 180 °C unos 40 minutos.','La receta rinde 4 porciones; ajusta las porciones que comerás.']),
R('r42','Sopa paraguaya',['almuerzo','cena'],6,60,[['hmaiz',200],['qparaguay',150],['cebolla',150],['huevo',150],['leche',250],['aceite',30]],['Mezcla la harina con huevos, leche, queso en cubos y la cebolla salteada.','Vierte en una fuente aceitada y hornea a 180 °C unos 45 minutos.','La receta rinde 6 porciones; adaptación casera.']),
R('r43','Lentejas con verduras',['almuerzo','cena'],2,40,[['lentejas',250],['zanahoria',80],['cebolla',50],['tomate',80],['aceite',8]],['Sofríe cebolla, tomate y zanahoria.','Agrega las lentejas cocidas y un poco de agua; cocina 15 minutos.']),
R('r44','Mousse de palta y cacao',['postre','colacion'],2,10,[['palta',100],['cacao',10],['leche',50]],['Procesa la palta con el cacao y la leche hasta que quede cremoso.','Endulza con edulcorante si lo deseas y enfría 30 minutos.']),
R('r45','Flan de huevo ligero',['postre','colacion'],3,45,[['huevo',150],['leche',200]],['Bate los huevos con la leche y edulcorante a gusto.','Cocina a baño María en el horno a 160 °C unos 35 minutos.']),
R('r46','Manzana al horno con canela',['postre','colacion'],1,25,[['manzana',150],['nueces',10]],['Hornea la manzana con canela a 180 °C unos 20 minutos.','Sirve con las nueces picadas.']),
R('r47','Budín de chía con frutillas',['postre','colacion'],2,5,[['chia',25],['leche',200],['frutilla',80]],['Mezcla chía y leche y deja reposar en la heladera 2 horas o toda la noche.','Sirve con frutillas.']),
R('r48','Ricota con canela y frutillas',['postre','colacion'],1,5,[['ricota',100],['frutilla',80]],['Mezcla la ricota con canela y sirve con las frutillas.']),
R('r49','Tostada integral con huevo y palta',['desayuno'],1,10,[['pan',50],['huevo',100],['palta',50],['tomate',40]],['Tuesta el pan.','Cocina los huevos a la plancha y sirve sobre la tostada con palta y tomate.']),
R('r50','Tostada con ricota y frutillas',['desayuno'],1,5,[['pan',40],['ricota',60],['frutilla',60]],['Unta la ricota sobre el pan tostado y agrega las frutillas.']),
R('r51','Licuado de banana, avena y leche',['desayuno'],1,5,[['avena',30],['banana',100],['leche',250]],['Licúa todos los ingredientes hasta que quede suave.']),
R('r52','Yogur con avena, chía y mamón',['desayuno'],1,5,[['yogur',200],['avena',30],['chia',10],['mamon',100]],['Mezcla el yogur con la avena y la chía.','Agrega el mamón en cubos.']),
R('r53','Panqueques de avena y huevo',['desayuno'],1,15,[['avena',40],['huevo',100],['banana',60],['aceite',3]],['Tritura la avena y mezcla con huevos y banana.','Cocina porciones pequeñas en sartén aceitada, 2 minutos por lado.']),
R('r54','Huevos con acelga y queso',['desayuno'],1,10,[['huevo',150],['acelga',80],['qparaguay',30],['aceite',5]],['Saltea la acelga cocida con el aceite.','Agrega los huevos y el queso y revuelve hasta que cuajen.']),
R('r55','Bowl de ricota con maní y mamón',['desayuno'],1,5,[['ricota',120],['mani',15],['mamon',120]],['Coloca la ricota en un bowl y agrega el mamón en cubos y el maní picado.']),
R('r56','Avena cocida con manzana y linaza',['desayuno'],1,10,[['avena',40],['leche',200],['lino',10],['manzana',80]],['Cocina la avena con la leche 4 a 5 minutos.','Agrega la manzana picada y la linaza.']),
R('r57','Mandioca con queso',['desayuno'],1,20,[['mandioca',100],['qparaguay',40]],['Hierve la mandioca hasta que esté tierna.','Sirve con el queso en trozos.']),
R('r58','Batido de frutilla, yogur y chía',['desayuno'],1,5,[['frutilla',150],['yogur',150],['leche',100],['chia',8]],['Licúa todo y sirve frío.']),
R('r59','Guayaba con maní',['colacion'],1,2,[['guayaba',100],['mani',20]],['Come la guayaba en trozos con el maní.']),
R('r60','Huevo duro con tomate',['colacion'],1,12,[['huevo',100],['tomate',60]],['Cocina los huevos 10 minutos.','Sirve con el tomate en rodajas.']),
R('r61','Bastones de verdura con ricota',['colacion'],1,5,[['zanahoria',60],['pepino',60],['ricota',50]],['Corta la zanahoria y el pepino en bastones.','Sirve con la ricota como dip.']),
R('r62','Queso Paraguay con melón',['colacion'],1,3,[['qparaguay',40],['melon',120]],['Sirve el queso en cubos junto con el melón.']),
R('r63','Garbanzos con pepino',['colacion'],1,5,[['garbanzos',100],['pepino',60]],['Mezcla los garbanzos cocidos con el pepino picado y unas gotas de limón.']),
R('r64','Yogur con linaza y melón',['colacion'],1,3,[['yogur',150],['lino',8],['melon',100]],['Mezcla el yogur con la linaza y agrega el melón.']),
R('r65','Palta con tomate',['colacion'],1,3,[['palta',70],['tomate',40]],['Sirve la palta en cubos con el tomate y limón.']),
R('r66','Nueces con frutillas',['colacion'],1,2,[['nueces',15],['frutilla',100]],['Come las nueces con las frutillas.']),
R('r67','Ensalada rápida de remolacha y huevo',['colacion'],1,10,[['remolacha',80],['huevo',50]],['Corta la remolacha cocida y el huevo duro y mezcla.']),
R('r68','Pan integral con ricota',['colacion'],1,3,[['pan',30],['ricota',50]],['Unta la ricota sobre el pan.']),
R('r69','Leche con cacao amargo',['colacion'],1,5,[['leche',200],['cacao',5]],['Calienta la leche y disuelve el cacao; endulza con edulcorante si deseas.']),
R('r70','Pomelo con yogur',['colacion'],1,3,[['pomelo',150],['yogur',100]],['Pela el pomelo y sirve con el yogur.']),
R('r71','Garbanzos guisados con acelga y huevo',['almuerzo','cena'],1,30,[['garbanzos',200],['acelga',100],['huevo',50],['cebolla',30],['aceite',8]],['Sofríe la cebolla y agrega la acelga y los garbanzos con un poco de agua.','Cocina 10 minutos y sirve con el huevo duro picado.']),
R('r72','Porotos con carne y verduras',['almuerzo'],1,40,[['porotos',200],['carne',100],['zanahoria',50],['cebolla',40],['aceite',5]],['Dora la carne en cubos con la cebolla.','Agrega los porotos cocidos, la zanahoria y un poco de agua; cocina 20 minutos.']),
R('r73','Berenjena rellena de carne molida',['almuerzo','cena'],1,40,[['berenjena',200],['molida',120],['tomate',60],['mozzarella',30]],['Abre las berenjenas cocidas y retira parte de la pulpa.','Mezcla la pulpa con carne molida cocida y tomate, rellena, cubre con queso y gratina 10 minutos.']),
R('r74','Arvejas con pollo',['almuerzo','cena'],1,25,[['arveja',150],['pollo',150],['zanahoria',50],['aceite',8]],['Saltea el pollo en cubos.','Agrega las arvejas y la zanahoria y cocina 8 minutos.']),
R('r75','Ensalada de chauchas, remolacha y atún',['almuerzo','cena'],1,15,[['chaucha',100],['remolacha',80],['atun',100],['lechuga',60],['aceite',8]],['Mezcla las verduras cocidas con el atún y la lechuga.','Alíña con el aceite.']),
R('r76','Garbanzos con pollo y espinaca',['almuerzo','cena'],1,25,[['garbanzos',150],['pollo',150],['espinaca',80],['aceite',8]],['Saltea el pollo en cubos.','Agrega los garbanzos y la espinaca y cocina 5 minutos.'])
];
